[pytest]
DJANGO_SETTINGS_MODULE = suplastock.settings
python_files = tests.py test_*.py *_test.py
addopts = -v --tb=short
testpaths = gestao

[coverage:run]
source = gestao
omit = 
    */migrations/*
    */tests/*
    */__pycache__/*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
show_missing = true

