# Generated by Django 5.2.9 on 2026-03-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
                migrations.CreateModel(
                    name='ContaPagar',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('descricao', models.CharField(max_length=255)),
                        ('categoria', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('internet', 'Internet'), ('telefone', 'Telefone'), ('salario', 'Salário'), ('impostos', 'Impostos'), ('marketing', 'Marketing'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=30)),
                        ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('data_vencimento', models.DateField()),
                        ('data_pagamento', models.DateField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                        ('observacoes', models.TextField(blank=True, null=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
                    ],
                    options={
                        'verbose_name': 'Conta a Pagar',
                        'verbose_name_plural': 'Contas a Pagar',
                        'db_table': 'gestao_contapagar',
                        'ordering': ['data_vencimento'],
                    },
                ),
                migrations.CreateModel(
                    name='ContaReceber',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('descricao', models.CharField(max_length=255)),
                        ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('data_vencimento', models.DateField()),
                        ('data_recebimento', models.DateField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                        ('observacoes', models.TextField(blank=True, null=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.cliente')),
                        ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda')),
                    ],
                    options={
                        'verbose_name': 'Conta a Receber',
                        'verbose_name_plural': 'Contas a Receber',
                        'db_table': 'gestao_contareceber',
                        'ordering': ['data_vencimento'],
                    },
                ),
    ]
