# Generated by Django 5.2.9 on 2026-03-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(blank=True, help_text='Forma de pagamento usada no recebimento', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='origem',
            field=models.CharField(choices=[('avulsa', 'Avulsa'), ('fiado', 'Venda Fiada')], default='avulsa', max_length=20),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='transacao_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da transação para vincular às vendas geradas', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ItemContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.contareceber')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Item da Conta a Receber',
                'verbose_name_plural': 'Itens da Conta a Receber',
                'db_table': 'gestao_itemcontareceber',
            },
        ),
    ]
