# Generated by Django 5.2.9 on 2026-03-23 14:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from datetime import date
from django.conf import settings
from django.db import migrations, models


def _normalizar_forma_pagamento(forma):
    valores_validos = {
        'Dinheiro',
        'Pix',
        'Cartão de Crédito',
        'Cartão de Débito',
        'Transferência',
    }
    aliases = {
        'dinheiro': 'Dinheiro',
        'pix': 'Pix',
        'cartao de credito': 'Cartão de Crédito',
        'cartão de crédito': 'Cartão de Crédito',
        'cartao_credito': 'Cartão de Crédito',
        'cartão_credito': 'Cartão de Crédito',
        'cartao de debito': 'Cartão de Débito',
        'cartão de débito': 'Cartão de Débito',
        'cartao_debito': 'Cartão de Débito',
        'cartão_debito': 'Cartão de Débito',
        'transferencia': 'Transferência',
        'transferência': 'Transferência',
    }
    chave = (forma or '').strip().lower()
    valor = aliases.get(chave, (forma or '').strip())
    return valor if valor in valores_validos else 'Dinheiro'


def _backfill_recebimentos_conta(apps, schema_editor):
    ContaReceber = apps.get_model('financeiro', 'ContaReceber')
    RecebimentoConta = apps.get_model('financeiro', 'RecebimentoConta')
    db_alias = schema_editor.connection.alias

    transacoes_duplicadas = (
        ContaReceber.objects.using(db_alias)
        .filter(origem='fiado')
        .exclude(transacao_id__isnull=True)
        .exclude(transacao_id='')
        .values('transacao_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )
    for item in transacoes_duplicadas:
        transacao_id = item['transacao_id']
        contas = list(
            ContaReceber.objects.using(db_alias)
            .filter(origem='fiado', transacao_id=transacao_id)
            .order_by('id')
        )
        for conta_duplicada in contas[1:]:
            conta_duplicada.transacao_id = f'{transacao_id}_dup_{conta_duplicada.id}'
            conta_duplicada.save(update_fields=['transacao_id'])

    contas_recebidas = (
        ContaReceber.objects.using(db_alias)
        .filter(status='recebido')
        .order_by('id')
    )
    for conta in contas_recebidas:
        if RecebimentoConta.objects.using(db_alias).filter(conta_id=conta.id).exists():
            continue
        if not conta.valor or conta.valor <= 0:
            continue
        data_recebimento = conta.data_recebimento or conta.data_vencimento or date.today()
        RecebimentoConta.objects.using(db_alias).create(
            conta_id=conta.id,
            valor=conta.valor,
            forma_pagamento=_normalizar_forma_pagamento(conta.forma_pagamento),
            data_recebimento=data_recebimento,
            observacoes='Registro histórico migrado automaticamente.',
        )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_contapagar_valor_alter_contareceber_valor_and_more'),
        ('vendas', '0002_alter_pagamento_valor_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Transferência', 'Transferência')], max_length=50)),
                ('data_recebimento', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recebimento de Conta',
                'verbose_name_plural': 'Recebimentos de Conta',
                'db_table': 'gestao_recebimentoconta',
                'ordering': ['-data_recebimento', '-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebido', 'Recebido'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='recebimentoconta',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='financeiro.contareceber'),
        ),
        migrations.AddField(
            model_name='recebimentoconta',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_conta_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_backfill_recebimentos_conta, _noop),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(origem='fiado', transacao_id__isnull=False)
                    & ~models.Q(transacao_id='')
                ),
                fields=('transacao_id',),
                name='uniq_contareceber_transacao_fiado',
            ),
        ),
    ]
