# Generated by Django 5.2.9 on 2026-03-23 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_recebimentoconta_alter_contareceber_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentoconta',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Chave de idempotencia para evitar registro duplicado de recebimento.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='recebimentoconta',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('conta', 'idempotency_key'), name='uniq_recebimentoconta_conta_idempotency'),
        ),
    ]
