# Generated by Django 5.2.9 on 2026-03-24 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_recebimentoconta_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('venda_a_vista', 'Venda à vista'), ('pagamento_fiado', 'Pagamento de fiado'), ('entrada_manual', 'Entrada manual'), ('despesa_operacional', 'Despesa operacional'), ('compra_fornecedor', 'Compra de fornecedor'), ('retirada', 'Retirada'), ('saida_manual', 'Saída manual')], max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('origem', models.CharField(default='Lançamento Manual', max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'db_table': 'gestao_movimentacaocaixa',
                'ordering': ['-data_movimentacao', '-criado_em', '-id'],
            },
        ),
    ]
