# Generated by Django 5.2.9 on 2026-03-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
                migrations.CreateModel(
                    name='Categoria',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=100)),
                    ],
                    options={
                        'db_table': 'gestao_categoria',
                    },
                ),
                migrations.CreateModel(
                    name='Fornecedor',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=255)),
                        ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                        ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('endereco', models.TextField(blank=True, null=True)),
                        ('ativo', models.BooleanField(default=True)),
                    ],
                    options={
                        'verbose_name': 'Fornecedor',
                        'verbose_name_plural': 'Fornecedores',
                        'db_table': 'gestao_fornecedor',
                    },
                ),
                migrations.CreateModel(
                    name='Produto',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=255)),
                        ('fornecedor_nome_legado', models.CharField(blank=True, help_text='Nome do fornecedor em produtos antigos', max_length=255, null=True)),
                        ('quantidade_comprada', models.IntegerField(default=0)),
                        ('estoque_atual', models.IntegerField(default=0)),
                        ('estoque_minimo', models.IntegerField(default=5, help_text='Quantidade mínima para alerta')),
                        ('lote', models.CharField(blank=True, max_length=100, null=True)),
                        ('data_fabricacao', models.DateField(blank=True, null=True)),
                        ('data_validade', models.DateField(blank=True, null=True)),
                        ('preco_custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('preco_venda_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('margem_lucro_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Margem de lucro em %', max_digits=5)),
                        ('data_compra', models.DateField()),
                        ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                        ('ativo', models.BooleanField(default=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('atualizado_em', models.DateTimeField(auto_now=True)),
                        ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria')),
                        ('fornecedor', models.ForeignKey(blank=True, help_text='Fornecedor principal do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
                    ],
                    options={
                        'db_table': 'gestao_produto',
                        'ordering': ['-criado_em'],
                    },
                ),
                migrations.CreateModel(
                    name='AlertaEstoque',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo_alerta', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('produto_vencido', 'Produto Vencido'), ('proximo_vencimento', 'Próximo ao Vencimento'), ('estoque_zerado', 'Estoque Zerado')], max_length=30)),
                        ('mensagem', models.TextField()),
                        ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizado', 'Visualizado'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='pendente', max_length=20)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('visualizado_em', models.DateTimeField(blank=True, null=True)),
                        ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                        ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                    ],
                    options={
                        'verbose_name': 'Alerta de Estoque',
                        'verbose_name_plural': 'Alertas de Estoque',
                        'db_table': 'gestao_alertaestoque',
                        'ordering': ['-criado_em'],
                    },
                ),
    ]
