# Generated by Django 5.2.9 on 2026-03-28 18:26

from django.db import migrations


def preencher_sku_produtos_existentes(apps, schema_editor):
    Produto = apps.get_model('estoque', 'Produto')

    def gerar_sku(nome):
        base = ''.join(ch for ch in (nome or '').upper() if ch.isalnum())[:3] or 'PRD'
        sequencia = 1
        while True:
            candidato = f'{base}-{sequencia:03d}'
            if not Produto.objects.filter(sku=candidato).exists():
                return candidato
            sequencia += 1

    for produto in Produto.objects.filter(sku__isnull=True):
        produto.sku = gerar_sku(produto.nome)
        produto.save(update_fields=['sku'])


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_sku_movimentacaoestoque'),
    ]

    operations = [
        migrations.RunPython(preencher_sku_produtos_existentes, reverse_noop),
    ]
