# Generated by Django 5.2.9 on 2026-03-14 20:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
                migrations.CreateModel(
                    name='Usuario',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                        ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                        ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                        ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('estoquista', 'Estoquista')], default='vendedor', max_length=20)),
                        ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                        ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                        ('ativo', models.BooleanField(default=True)),
                        ('data_criacao', models.DateTimeField(auto_now_add=True)),
                        ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                        ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                        ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                    ],
                    options={
                        'verbose_name': 'Usuário',
                        'verbose_name_plural': 'Usuários',
                        'db_table': 'gestao_usuario',
                        'ordering': ['-date_joined'],
                    },
                    managers=[
                        ('objects', django.contrib.auth.models.UserManager()),
                    ],
                ),
                migrations.CreateModel(
                    name='TokenRecuperacaoSenha',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token', models.CharField(max_length=100, unique=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('usado', models.BooleanField(default=False)),
                        ('expira_em', models.DateTimeField()),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Token de Recuperação',
                        'verbose_name_plural': 'Tokens de Recuperação',
                        'db_table': 'gestao_tokenrecuperacaosenha',
                    },
                ),
                migrations.CreateModel(
                    name='HistoricoAcesso',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo_acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_falho', 'Tentativa de Login Falha'), ('criar', 'Criação'), ('editar', 'Edição'), ('deletar', 'Exclusão'), ('visualizar', 'Visualização')], max_length=20)),
                        ('descricao', models.TextField()),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                        ('user_agent', models.TextField(blank=True, null=True)),
                        ('data_hora', models.DateTimeField(auto_now_add=True)),
                        ('modelo_afetado', models.CharField(blank=True, help_text='Modelo que foi afetado pela ação', max_length=100, null=True)),
                        ('objeto_id', models.IntegerField(blank=True, help_text='ID do objeto afetado', null=True)),
                        ('dados_adicionais', models.JSONField(blank=True, help_text='Dados extras em JSON', null=True)),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_acessos', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Histórico de Acesso',
                        'verbose_name_plural': 'Históricos de Acessos',
                        'db_table': 'gestao_historicoacesso',
                        'ordering': ['-data_hora'],
                        'indexes': [models.Index(fields=['-data_hora'], name='gestao_hist_data_ho_74d8d3_idx'), models.Index(fields=['usuario', '-data_hora'], name='gestao_hist_usuario_c14c0e_idx')],
                    },
                ),
    ]
