# Generated by Django 5.2.9 on 2026-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrador'),
                    ('developer', 'Desenvolvedor / Auditor'),
                    ('vendedor', 'Vendedor'),
                    ('estoquista', 'Estoquista'),
                ],
                default='vendedor',
                max_length=20,
            ),
        ),
    ]
