# Generated by Django 5.2.9 on 2026-03-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
                migrations.CreateModel(
                    name='Cliente',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('codigo', models.CharField(blank=True, help_text='Código único do cliente', max_length=20, null=True, unique=True)),
                        ('nome', models.CharField(max_length=255)),
                        ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                        ('endereco', models.TextField(blank=True, null=True)),
                        ('data_cadastro', models.DateField(auto_now_add=True)),
                        ('ativo', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'gestao_cliente',
                    },
                ),
                migrations.CreateModel(
                    name='Venda',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantidade_vendida', models.IntegerField()),
                        ('preco_venda_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('data_venda', models.DateField(auto_now_add=True)),
                        ('status_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Parcial', 'Parcial'), ('Pendente', 'Pendente')], default='Pago', max_length=20)),
                        ('transacao_id', models.CharField(blank=True, db_index=True, help_text='ID único para agrupar produtos da mesma venda', max_length=50, null=True)),
                        ('cliente_nome_legado', models.CharField(blank=True, help_text='Nome do cliente em vendas antigas', max_length=255, null=True)),
                        ('forma_pagamento_legado', models.CharField(blank=True, help_text='Forma de pagamento em vendas antigas', max_length=50, null=True)),
                        ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.cliente')),
                        ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                    ],
                    options={
                        'db_table': 'gestao_venda',
                    },
                ),
                migrations.CreateModel(
                    name='Pagamento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('forma_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Dinheiro', 'Dinheiro'), ('Transferência', 'Transferência')], max_length=50)),
                        ('data_pagamento', models.DateField()),
                        ('observacoes', models.TextField(blank=True, null=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.cliente')),
                        ('venda', models.ForeignKey(blank=True, help_text='Venda específica relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda')),
                    ],
                    options={
                        'verbose_name': 'Pagamento',
                        'verbose_name_plural': 'Pagamentos',
                        'db_table': 'gestao_pagamento',
                        'ordering': ['-data_pagamento', '-criado_em'],
                    },
                ),
    ]
