# Generated by Django 5.2.9 on 2026-03-28 16:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_pagamento_valor_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de desconto aplicado no item da venda', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total de desconto aplicado no item da venda', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='venda',
            name='preco_original_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário original antes de desconto', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
